root: true
env:
  browser: true
  es6: true
  node: true
extends:
  # - standard
  - 'plugin:vue/essential'
  - '@vue/prettier'
  # - 'prettier/standard'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  parser: 'babel-eslint'
  ecmaVersion: 2018
  sourceType: module
rules: {}
settings:
  react:
    version: 'detect'
